import type { Metadata } from 'next';
import { ArrowRight,ArrowUpRight,Ruler,ClipboardList,MessageCircle } from 'lucide-react';
import { business } from '@/lib/catalog';
import { categories,catalogItems } from '@/lib/presentation';
import ProductCards from '@/components/product-cards';
import ProductImage from '@/components/product-image';
export const metadata:Metadata={title:'ofirma | Fabrika İçi Taşıma ve Özel Üretim Ekipmanları',description:'ofirma; fabrika içi taşıma, malzeme yönetimi, kalıp ve atölye yardımcı ekipmanlarını ihtiyaca göre üretir. Fotoğraf, numune veya ölçülerle teklif alın.',alternates:{canonical:business.siteUrl}};
export default function Home(){return <main id="main">
 <section className="company-hero"><div className="wrap company-hero-grid"><div className="company-hero-copy"><p className="overline">OFİRMA ENDÜSTRİYEL EKİPMANLAR</p><h1>Üretim alanınız için,<br/><em>özel taşıma çözümleri.</em></h1><p>Fabrika içi taşıma kasaları, talaş ve hurda arabaları, profil taşıma ekipmanları ve atölye yardımcıları. Fotoğraf, numune veya bildiğiniz ölçülerle başlayalım.</p><div className="company-hero-actions"><a className="cta" href="/fabrika-ici-tasima">Taşıma çözümlerini keşfedin <ArrowRight size={20}/></a><a href="/iletisim">İhtiyacınızı anlatın <ArrowUpRight size={18}/></a></div></div><div className="company-hero-product"><ProductImage id="metal-tasima-kasasi" title="Metal taşıma kasası" priority/><a href="/metal-tasima-kasasi"><span><small>FABRİKA İÇİ TAŞIMA / ÖZEL ÖLÇÜ</small>Metal taşıma kasası</span><ArrowUpRight size={28}/></a></div></div></section>
 <section className="category-band"><div className="wrap">{categories.map((category,index)=><a href={category.id==='fabrika-tasima'?'/fabrika-ici-tasima':'/urunler#'+category.id} key={category.id}><span>0{index+1}</span><strong>{category.title}</strong><ArrowUpRight size={20}/></a>)}</div></section>
 <section className="company-products wrap" id="urunler"><div className="company-section-heading"><div><p className="overline">ÜRÜNLERİMİZ</p><h2>Fabrikanızdaki akışı birlikte kolaylaştıralım.</h2></div><a href="/urunler">Tüm ürünler <ArrowUpRight size={20}/></a></div><div id="diger-urunler"><ProductCards items={catalogItems}/></div></section>
 <section className="company-about"><div className="wrap company-about-grid"><div><p className="overline">OFİRMA HAKKINDA</p><h2>Standart ürün değil,<br/><span>işinize uyan çözüm.</span></h2><p>ofirma, Merzifon / Amasya merkezli olarak Samsun, Çorum ve Tokat çevresindeki üretim işletmeleri için fabrika içi taşıma, kalıp ve atölye yardımcı ekipmanları geliştirir. İhtiyacı parçanın, yükün ve kullanım alanının gerçek koşullarıyla ele alırız.</p><a className="text-link" href="/kurumsal">Çalışma yaklaşımımız <ArrowUpRight size={18}/></a></div><div className="about-principles">{[[Ruler,'Ölçüye dayalı değerlendirme','Mevcut parçanıza veya kullanım alanınıza ait ölçülerle başlayın.'],[ClipboardList,'Taşıma sürecine göre tasarım','Yük, istifleme, geçiş ve boşaltma koşullarını birlikte netleştirelim.'],[MessageCircle,'Fotoğraf veya numuneyle başlayın','Teknik resim şart değil; fotoğraf ve numunenizle teklif isteyin.']].map(([Icon,title,text])=>{const I=Icon as typeof Ruler;return <article key={title as string}><I size={25}/><div><h3>{title as string}</h3><p>{text as string}</p></div></article>;})}</div></div></section>
 <section className="wrap case-index"><article><img src="/images/calisma-sebze-dograma/bicak-seti.jpg" width="1496" height="1496" loading="lazy" alt="Sebze doğrama makinesi kesim diskleri"/><div><p className="overline">GERÇEK UYGULAMA</p><h2>Sebze doğrama makinesi bıçak değişimi</h2><p>Makine restorasyonu hizmetimizden bir örnek. Çalışmanın gerçek fotoğraflarını inceleyin.</p><a className="cta" href="/ornek-calismalar/sebze-dograma-bicaklari">Çalışmayı inceleyin <ArrowUpRight size={18}/></a></div></article></section>
 <section className="company-contact-band" id="teklif"><div className="wrap"><div><p className="overline">PROJENİZİ KONUŞALIM</p><h2>Aradığınız ekipman için<br/>birlikte başlayalım.</h2></div><a className="light-cta" href="/iletisim">Teklif ve bilgi alın <ArrowUpRight size={22}/></a></div></section>
 </main>;}
