import QuoteForm from './quote-form';
import { ArrowDown, ArrowUpRight, MessageCircle, Ruler, FileText } from 'lucide-react';
import { business, products } from '@/lib/catalog';
export default function Home() { return <>
<div className="topline"><span>MERZİFON / AMASYA</span><span>Özel ölçü · Teknik değerlendirme · Teklif</span></div>
<header className="header wrap"><a href="#" className="brand" aria-label="ofirma ana sayfa">ofirma<span>●</span></a><nav aria-label="Ana menü"><a href="#urun">Konveyör rulosu</a><a href="#olcu">Ölçü rehberi</a><a href="#surec">Nasıl ilerleriz?</a></nav><a className="header-cta" href="#teklif">Teklif iste <ArrowUpRight size={18}/></a></header>
<main id="main"><section className="hero wrap" id="urun"><div className="hero-copy"><p className="eyebrow"><span className="orange-dot"/> KONVEYÖR BİLEŞENLERİ / 01</p><h1>Hattınıza uygun.<br/><span>Ölçünüze özel.</span></h1><p className="lead">{products[0].title} için ihtiyacınızı birlikte netleştirelim. Elinizdeki rulonun ölçülerini veya teknik resmini paylaşarak başlayın.</p><div className="hero-actions"><a className="cta" href="#teklif">Rulonuz için teklif isteyin <ArrowUpRight size={20}/></a><a className="text-link" href="#olcu">Nasıl ölçülür? <ArrowDown size={17}/></a></div><div className="hero-tags"><span>Özel ölçü talebi</span><span>Yedek rulo değerlendirmesi</span></div></div>
<div className="drawing-panel"><div className="drawing-heading"><span>ÖLÇÜ REFERANSI</span><span>01 / RULO</span></div><svg viewBox="0 0 640 390" role="img" aria-labelledby="drawing-title drawing-desc"><title id="drawing-title">Konveyör rulosunun ölçü şeması</title><desc id="drawing-desc">B gövde boyu, D dış çap, d mil çapı, L toplam mil boyu. Şema ölçekli değildir.</desc><defs><pattern id="grid" width="24" height="24" patternUnits="userSpaceOnUse"><path d="M24 0H0V24" fill="none" stroke="#fff" strokeOpacity=".05"/></pattern><marker id="arrow" markerWidth="6" markerHeight="6" refX="3" refY="3" orient="auto-start-reverse"><path d="M0 0L6 3L0 6" fill="#ff8050"/></marker></defs><rect width="640" height="390" fill="url(#grid)"/><g fill="none" stroke="#b4c1cc" strokeWidth="2"><path d="M90 188H150V162H490V188H552V208H490V234H150V208H90Z"/><path d="M166 162V234M474 162V234M150 188V208M490 188V208"/><path d="M60 198H580" strokeDasharray="10 6" stroke="#738590" strokeWidth="1"/></g><g stroke="#ff8050" fill="none" strokeWidth="1"><path d="M150 151V94M490 151V94M90 217V308M552 217V308M500 162H607M500 234H607"/><path d="M155 105H485M95 294H547M594 168V228" markerStart="url(#arrow)" markerEnd="url(#arrow)"/><path d="M83 188H64M83 208H64M70 180V216"/></g><g fill="#ff9a74" fontSize="18" fontFamily="monospace" textAnchor="middle"><text x="320" y="91">B · Gövde boyu</text><text x="320" y="325">L · Toplam mil boyu</text><text x="618" y="204">D</text><text x="50" y="204">d</text></g><g fill="#b0bec8" fontSize="14" fontFamily="monospace"><text x="29" y="363">YAN GÖRÜNÜŞ</text><text x="440" y="363">ÖLÇEKLİ DEĞİLDİR</text></g></svg><div className="drawing-footer"><span><Ruler size={16}/> D / B / d / L</span><span>Her detay, doğru eşleşme için.</span></div></div></section>
<div className="spec-strip wrap"><div><span>ÜRÜN</span><strong>Konveyör rulosu</strong></div><div><span>İHTİYAÇ</span><strong>Yeni hat veya yedek parça</strong></div><div><span>BAŞLANGIÇ</span><strong>Ölçü, fotoğraf, teknik resim</strong></div><a href="#teklif">İhtiyacınızı paylaşın <ArrowUpRight size={23}/></a></div>
<section className="section wrap" id="olcu"><div className="section-head"><p className="eyebrow">01 — TEKNİK BİLGİLER</p><h2>Doğru teklif,<br/>doğru ölçüyle başlar.</h2><p>Bildiklerinizi paylaşmanız yeterli. Eksik ölçüleri ve bağlantı detaylarını görüşmede netleştirebiliriz.</p></div><div className="measure-grid">{[['D','Dış çap','Rulo gövdesinin dıştan dışa çapı.'],['B','Gövde boyu','Yalnızca dönen gövdenin uçtan uca uzunluğu.'],['d','Mil çapı','Gövde dışına çıkan milin çapı.'],['L','Toplam mil boyu','Milin iki ucu arasındaki toplam uzunluk.']].map(([letter,title,desc])=><article key={letter}><span className="measure-letter">{letter}</span><h3>{title}</h3><p>{desc}</p><span className="unit">Birim: mm</span></article>)}</div><p className="technical-note"><FileText size={18}/> Mil ucu, rulman, malzeme, yük ve çalışma ortamı da seçimde değerlendirilir. Şema bir ölçü rehberidir; üretim teknik resmi değildir.</p></section>
<section className="process-section" id="surec"><div className="wrap"><div className="process-heading"><p className="eyebrow">02 — BİRLİKTE NETLEŞTİRELİM</p><h2>Parçadan başlayın.<br/>Detayları konuşalım.</h2></div><div className="steps">{[['01','İhtiyacınızı paylaşın','Mevcut rulonun ölçülerini, kullanım yerini ve ihtiyacınız olan adedi belirtin.'],['02','Detayları netleştirelim','Malzeme, mil bağlantısı ve çalışma koşullarını teknik resim veya fotoğraf üzerinden görüşelim.'],['03','Teklifi değerlendirin','Üretim uygunluğu, fiyat ve teslim süresi netleştiğinde teklif üzerinden karar verin.']].map(([num,title,desc])=><article key={num}><span>{num}</span><h3>{title}</h3><p>{desc}</p></article>)}</div></div></section>
<section className="quote-section wrap" id="teklif"><div className="quote-intro"><p className="eyebrow">03 — TEKLİF TALEBİ</p><h2>Ölçü sizden.<br/><span>İlk adım birlikte.</span></h2><p>Formu doldurun; bilgileriniz WhatsApp mesajına dönüşsün. Fotoğrafınızı veya teknik resminizi açılan sohbete ekleyebilirsiniz.</p><a className="contact" href={'https://wa.me/'+business.whatsapp} target="_blank" rel="noopener noreferrer"><MessageCircle/><div><small>Doğrudan WhatsApp</small><strong>{business.phoneDisplay}</strong></div><ArrowUpRight/></a><p className="small-note">Fiyat ve üretim uygunluğu teknik değerlendirme sonrasında netleşir.</p></div><QuoteForm/></section>
<section className="faq wrap"><p className="eyebrow">SIK SORULANLAR</p><div>{[['Bütün ölçüleri bilmiyorsam ne yapmalıyım?','Bildiğiniz ölçüleri girin. Rulonun genel görünüşünü ve mil uçlarını gösteren fotoğrafları WhatsApp görüşmesine ekleyebilirsiniz.'],['Fotoğraf veya teknik resmi nasıl paylaşırım?','Formdan WhatsApp’a geçtikten sonra dosyanızı sohbetin ek düğmesiyle gönderin. Bu sayfa dosya yüklemez ve mesajınızı otomatik göndermez.'],['Fiyatı ve teslim süresini ne belirler?','Ölçüler, malzeme, adet, mil ve rulman detayları ile çalışma koşulları birlikte değerlendirilir. Fiyat ve teslim süresi teklif aşamasında netleşir.']].map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></section>
</main><footer className="footer wrap"><a className="brand" href="#">ofirma<span>●</span></a><p>Konveyör rulosu · Özel ölçü talepleri</p><a href={'tel:'+business.phone}>{business.phoneDisplay} <ArrowUpRight size={16}/></a><span>© {new Date().getFullYear()} ofirma</span></footer></>; }
