import type { Metadata } from 'next';
import { ArrowRight,ArrowUpRight,Ruler,ClipboardList,MessageCircle } from 'lucide-react';
import { business } from '@/lib/catalog';
import { categories,catalogItems } from '@/lib/presentation';
import ProductCards from '@/components/product-cards';
import ProductImage from '@/components/product-image';
export const metadata:Metadata={title:'ofirma | Konveyör, Taşıma ve Depolama Ekipmanları',description:'ofirma endüstriyel ekipmanlar. Konveyör ruloları, taşıma arabaları, sac rafları ve forklift ekipmanları. Ürünleri inceleyin, ihtiyacınıza göre teklif isteyin.',alternates:{canonical:business.siteUrl}};
export default function Home(){return <main id="main">
 <section className="company-hero"><div className="wrap company-hero-grid"><div className="company-hero-copy"><p className="overline">OFİRMA ENDÜSTRİYEL EKİPMANLAR</p><h1>Üretimin her adımında,<br/><em>ihtiyacınıza uygun ekipman.</em></h1><p>Konveyör bileşenleri, taşıma arabaları ve depolama ekipmanları. Ürününüzü seçin, ölçü ve kullanım detaylarını birlikte netleştirelim.</p><div className="company-hero-actions"><a className="cta" href="/urunler">Ürünlerimizi keşfedin <ArrowRight size={20}/></a><a href="/kurumsal">ofirma’yı tanıyın <ArrowUpRight size={18}/></a></div></div><div className="company-hero-product"><ProductImage id="konveyor-rulosu" title="Konveyör rulosu" priority/><a href="/konveyor-rulosu"><span><small>ÖZEL ÖLÇÜ / YEDEK PARÇA</small>Konveyör rulosu</span><ArrowUpRight size={28}/></a></div></div></section>
 <section className="category-band"><div className="wrap">{categories.map((category,index)=><a href={'/urunler#'+category.id} key={category.id}><span>0{index+1}</span><strong>{category.title}</strong><ArrowUpRight size={20}/></a>)}</div></section>
 <section className="company-products wrap" id="urunler"><div className="company-section-heading"><div><p className="overline">ÜRÜNLERİMİZ</p><h2>İşinize uygun çözümleri keşfedin.</h2></div><a href="/urunler">Tüm ürünler <ArrowUpRight size={20}/></a></div><div id="diger-urunler"><ProductCards items={catalogItems}/></div></section>
 <section className="company-about"><div className="wrap company-about-grid"><div><p className="overline">OFİRMA HAKKINDA</p><h2>Önce ihtiyacı anlarız.<br/><span>Detayları birlikte netleştiririz.</span></h2><p>ofirma, Merzifon / Amasya odağında konveyör, taşıma ve depolama ekipmanı taleplerini bir araya getirir. Her talebi ürünün ölçüsü, kullanım yeri ve çalışma koşullarıyla birlikte ele alırız.</p><a className="text-link" href="/kurumsal">Çalışma yaklaşımımız <ArrowUpRight size={18}/></a></div><div className="about-principles">{[[Ruler,'Ölçüye dayalı değerlendirme','Mevcut parçanıza veya kullanım alanınıza ait ölçülerle başlayın.'],[ClipboardList,'Ürüne özel teknik bilgiler','Her ürün için gerekli soruları ayrı ayrı ele alalım.'],[MessageCircle,'Doğrudan iletişim','Fotoğraf ve teknik resimlerinizi WhatsApp üzerinden paylaşın.']].map(([Icon,title,text])=>{const I=Icon as typeof Ruler;return <article key={title as string}><I size={25}/><div><h3>{title as string}</h3><p>{text as string}</p></div></article>;})}</div></div></section>
 <section className="company-contact-band" id="teklif"><div className="wrap"><div><p className="overline">PROJENİZİ KONUŞALIM</p><h2>Aradığınız ekipman için<br/>birlikte başlayalım.</h2></div><a className="light-cta" href="/iletisim">Teklif ve bilgi alın <ArrowUpRight size={22}/></a></div></section>
 </main>;}
