// Mekanikya örnek ürün düzeni görselleri
export const factoryOptionImages: Record<string, {src:string; alt:string}> = {
  'Tekerlekli taşıma altlığı': {src:'/images/factory-options/misumi-metal-dolly.jpg',alt:'Mekanikya ayrı tekerlekli kasa altlığı düzeni'},
  'Açık üstlü kasa': {src:'/images/factory-options/misumi-metal-open.jpg',alt:'Mekanikya açık üstlü sac kasa düzeni'},
  'Ön erişimli kasa': {src:'/images/factory-options/misumi-metal-front.jpg',alt:'Mekanikya çıkarılabilir ön panelli kasa düzeni'},
  'İstif düzenli kasa': {src:'/images/factory-options/misumi-metal-stacked.jpg',alt:'Mekanikya üst üste istiflenmiş kasa düzeni'},
  'Açık hazneli araba': {src:'/images/factory-options/misumi-sakae-scrap.jpg',alt:'Mekanikya açık hazneli talaş arabası düzeni'},
  'Devirme düzenli araba': {src:'/images/factory-options/misumi-scrap-tipping.jpg',alt:'Mekanikya devirme düzenli talaş arabası düzeni'},
  'Forklift cepli ve vinç kulaklı kasa': {src:'/images/factory-options/misumi-metal-crane-forklift.jpg',alt:'Mekanikya vinç kulaklı ve forklift cepli kasa düzeni'},
  'Modüler ve bölmeli şase': {src:'/images/factory-options/misumi-profile-modular.jpg',alt:'Mekanikya modüler ve bölmeli profil taşıma arabası düzeni'},
  'İki yandan tutamaklı': {src:'/images/factory-options/misumi-profile-side-handles.jpg',alt:'Mekanikya iki yandan tutamaklı uzun malzeme arabası düzeni'},
  'Boru ve uzun malzeme arabası': {src:'/images/factory-options/misumi-profile-pipe-cart.jpg',alt:'Mekanikya yan destekli boru ve uzun malzeme arabası düzeni'},
  'Çelik platformlu araba': {src:'/images/factory-options/misumi-profile-steel-platform.jpg',alt:'Mekanikya çelik platformlu uzun malzeme arabası düzeni'},
  'Çok bölmeli sac ve panel arabası': {src:'/images/factory-options/misumi-sheet-multi-slot.jpg',alt:'Mekanikya çok bölmeli dikey plaka arabası düzeni'},
  'Tel kafesli havalandırmalı araba': {src:'/images/factory-options/misumi-textile-mesh-cage.jpg',alt:'Mekanikya tel kafesli havalandırmalı tekstil arabası düzeni'},
  'Tek rulolu yükseklik ayarlı sehpa': {src:'/images/factory-options/misumi-roller-single-stand.jpg',alt:'Mekanikya tek rulolu yükseklik ayarlı destek sehpası düzeni'},
  'Tekli ve çiftli tüp arabası': {src:'/images/factory-options/misumi-cylinder-single-cart.jpg',alt:'Mekanikya paslanmaz çelik tüp taşıma arabası düzeni'},
  'Sabit tüp depolama kabini': {src:'/images/factory-options/misumi-cylinder-storage-box.jpg',alt:'Mekanikya tüp depolama kabini düzeni'},
  'Kombine kaynak seti arabası': {src:'/images/factory-options/misumi-cylinder-dual-welding.jpg',alt:'Mekanikya ikili tüp taşıma arabası düzeni'},
};
