// Real product examples. Source records are kept with the project notes.
export const factoryOptionImages: Record<string, {src:string; alt:string}> = {
  'Tekerlekli taşıma altlığı': {src:'/images/factory-options/misumi-metal-dolly.jpg',alt:'MISUMI TRUSCO VJ-46C ayrı tekerlekli kasa altlığı; kasa dahil değil'},
  'Açık üstlü kasa': {src:'/images/factory-options/misumi-metal-open.jpg',alt:'MISUMI kataloğundaki TRUSCO VJ-453 açık üstlü sac kasa örneği'},
  'Ön erişimli kasa': {src:'/images/factory-options/misumi-metal-front.jpg',alt:'MISUMI kataloğundaki TRUSCO VJ-455 çıkarılabilir ön panelli kasa örneği'},
  'İstif düzenli kasa': {src:'/images/factory-options/misumi-metal-stacked.jpg',alt:'MISUMI kataloğundaki TRUSCO Mini Cargo üst üste istiflenmiş kasa kullanım örneği'},
  'Açık hazneli araba': {src:'/images/factory-options/misumi-sakae-scrap.jpg',alt:'MISUMI kataloğundaki Sakae açık hazneli talaş arabası örneği'},
  'Devirme düzenli araba': {src:'/images/factory-options/misumi-scrap-tipping.jpg',alt:'MISUMI kataloğundaki TRUSCO VSP-120 devirme düzenli talaş arabası örneği'},
  'Forklift cepli ve vinç kulaklı kasa': {src:'/images/factory-options/misumi-metal-crane-forklift.jpg',alt:'MISUMI kataloğundaki TRUSCO Mini Cargo vinç kulaklı ve forklift cepli kasa örneği'},
  'Modüler ve bölmeli şase': {src:'/images/factory-options/misumi-profile-modular.jpg',alt:'MISUMI kataloğundaki SUS GFM-439 modüler ve bölmeli profil taşıma arabası örneği'},
  'İki yandan tutamaklı': {src:'/images/factory-options/misumi-profile-side-handles.jpg',alt:'MISUMI kataloğundaki Hanaoka Sharyo DA-P iki yandan tutamaklı uzun malzeme arabası örneği'},
  'Boru ve uzun malzeme arabası': {src:'/images/factory-options/misumi-profile-pipe-cart.jpg',alt:'MISUMI kataloğundaki Supermate LC-6001 yan destekli boru ve uzun malzeme arabası örneği'},
  'Çelik platformlu araba': {src:'/images/factory-options/misumi-profile-steel-platform.jpg',alt:'MISUMI kataloğundaki Sakae RT-126 çelik platformlu uzun malzeme arabası örneği'},
  'Çok bölmeli sac ve panel arabası': {src:'/images/factory-options/misumi-sheet-multi-slot.jpg',alt:'MISUMI kataloğundaki KAISER 927565/927566 çok bölmeli dikey plaka arabası kullanım örneği'},
  'Kompakt atölye sac arabası': {src:'/images/factory-options/misumi-sheet-compact.jpg',alt:'MISUMI kataloğundaki TRUSCO ITA-1 kompakt atölye sac ve plaka taşıma arabası örneği'},
  'Tel kafesli havalandırmalı araba': {src:'/images/factory-options/misumi-textile-mesh-cage.jpg',alt:'MISUMI kataloğundaki Ishikawa Seisakusho 107/307 tel kafesli havalandırmalı tekstil ve çamaşırhane arabası örneği'},
  'Kademeli ön panelli araba': {src:'/images/factory-options/misumi-textile-drop-front.jpg',alt:'MISUMI kataloğundaki TRUSCO Donkey Cart katlanır kademeli ön panelli tekstil ve malzeme arabası örneği'},
  'Tek rulolu yükseklik ayarlı sehpa': {src:'/images/factory-options/misumi-roller-single-stand.jpg',alt:'MISUMI kataloğundaki ESCO / RIDGID CJ-99 tek rulolu yükseklik ayarlı boru ve profil sehpası örneği'},
  'Geniş tablalı profil sehpası': {src:'/images/factory-options/misumi-roller-wide-stand.jpg',alt:'MISUMI kataloğundaki ASTAGE WRS-1 geniş temas rulolu yükseklik ayarlı profil sehpası örneği'},
  'Tekli ve çiftli tüp arabası': {src:'/images/factory-options/misumi-cylinder-single-cart.jpg',alt:'MISUMI kataloğundaki TRUSCO ASUB-70 paslanmaz çelik tüp taşıma arabası örneği'},
  'Sabit tüp depolama kabini': {src:'/images/factory-options/misumi-cylinder-storage-box.jpg',alt:'MISUMI kataloğundaki Daiken 20 kg propan/LPG tüp depolama kabini örneği'},
  'Kombine kaynak seti arabası': {src:'/images/factory-options/misumi-cylinder-dual-welding.jpg',alt:'MISUMI kataloğundaki Kamimaru KS-O-LP20 oksijen ve LPG ikili tüp taşıma arabası örneği'},
};
