import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import { ArrowUpRight, MessageCircle, ArrowLeft } from 'lucide-react';
import { additionalProducts } from '@/lib/additional-products';
import { business } from '@/lib/catalog';
import ProductInquiry from '@/components/product-inquiry';
type Props={params:Promise<{product:string}>};
export function generateStaticParams(){return additionalProducts.map(product=>({product:product.id}));}
export async function generateMetadata({params}:Props):Promise<Metadata>{const {product:id}=await params;const product=additionalProducts.find(item=>item.id===id);if(!product)return {title:'Ürün bulunamadı | ofirma'};return {title:product.title+' | ofirma',description:product.description,alternates:{canonical:business.siteUrl+product.href}};}
export default async function ProductPage({params}:Props){
 const {product:id}=await params;const product=additionalProducts.find(item=>item.id===id);if(!product)notFound();
 const index=additionalProducts.findIndex(item=>item.id===id)+2;
 return <><div className="topline"><span>MERZİFON / AMASYA</span><span>Ürüne özel değerlendirme · Teklif</span></div><header className="header wrap"><a className="brand" href="/">ofirma<span>●</span></a><nav aria-label="Ana menü"><a href="/#urunler">Ürünler</a><a href="#bilgiler">Teknik bilgiler</a><a href="#teklif">İletişim</a></nav><a className="header-cta" href="#teklif">Teklif iste <ArrowUpRight size={18}/></a></header>
 <main id="main"><div className="wrap breadcrumb"><a href="/#diger-urunler"><ArrowLeft size={16}/> Ürün kataloğu</a><span>/</span><span>{product.title}</span></div>
 <section className="equipment-hero wrap"><div><p className="eyebrow"><span className="orange-dot"/>{product.category.toLocaleUpperCase('tr-TR')}</p><h1>{product.title}</h1><p className="lead">{product.description}</p><a className="cta" href="#teklif">İhtiyacınızı paylaşın <ArrowUpRight size={20}/></a></div><aside className="equipment-brief"><div className="brief-label"><span>TEKLİFE BAŞLANGIÇ</span><span>{String(index).padStart(2,'0')}</span></div><h2>Önce ihtiyacınızı<br/>tanımlayalım.</h2><ol>{product.checks.map((check,i)=><li key={check.title}><span>{String(i+1).padStart(2,'0')}</span>{check.title}</li>)}</ol><p>Ölçüler ve kullanım bilgileriyle değerlendirme yapılır; fiyat ve teslim süresi teklif aşamasında netleşir.</p></aside></section>
 <section className="equipment-info wrap" id="bilgiler"><div className="section-head"><p className="eyebrow">TEKNİK DEĞERLENDİRME</p><h2>Doğru sorular,<br/>net bir ihtiyaç.</h2><p>Bildiklerinizle başlayın. Eksik detayları fotoğraf, teknik resim veya mevcut ekipman bilgisiyle tamamlayabiliriz.</p></div><div className="equipment-checks">{product.checks.map((check,i)=><article key={check.title}><span>{String(i+1).padStart(2,'0')}</span><h3>{check.title}</h3><p>{check.text}</p></article>)}</div><div className="equipment-note"><p>{product.note}</p></div><div className="use-cases"><span>İlgili kullanım alanları</span>{product.uses.map(use=><span key={use}>{use}</span>)}</div></section>
 <section className="quote-section wrap" id="teklif"><div className="quote-intro"><p className="eyebrow">{String(index).padStart(2,'0')} / TEKLİF TALEBİ</p><h2>İhtiyacınızı yazın.<br/><span>Detayları görüşelim.</span></h2><p>Bu form {product.title.toLocaleLowerCase('tr-TR')} için hazırlanmıştır. Talep bilgileri tek bir WhatsApp mesajında toplanır.</p><a className="contact" href={'https://wa.me/'+business.whatsapp} target="_blank" rel="noopener noreferrer"><MessageCircle/><div><small>Doğrudan WhatsApp</small><strong>{business.phoneDisplay}</strong></div><ArrowUpRight/></a><p className="small-note">Özel ölçü, yük kapasitesi ve kullanım uygunluğu talebe göre değerlendirilir. Bu sayfa kesin kapasite, stok veya teslim süresi taahhüdü içermez.</p></div><ProductInquiry product={product}/></section>
 <section className="faq wrap"><p className="eyebrow">TEKLİF ÖNCESİNDE</p><div><details><summary>Bütün ölçüleri bilmiyorsam?<span>+</span></summary><p>Bilmediğiniz alanları boş bırakabilirsiniz. Mevcut ürüne veya kullanım alanına ait fotoğrafları WhatsApp görüşmesine ekleyin.</p></details><details><summary>Sayfadaki ürün için özel ölçü isteyebilir miyim?<span>+</span></summary><p>İhtiyacınız olan ölçüleri ve kullanım koşullarını belirtin. Üretim uygunluğu teknik değerlendirmeden sonra netleşir.</p></details><details><summary>Teknik resim nasıl paylaşılır?<span>+</span></summary><p>Teklif mesajıyla WhatsApp’ı açtıktan sonra dosyayı sohbetin ek düğmesiyle iletin. Bu site dosya yüklemez.</p></details></div></section></main>
 <footer className="footer wrap"><a className="brand" href="/">ofirma<span>●</span></a><a href="/#urunler">Tüm ürünler <ArrowUpRight size={16}/></a><a href={'tel:'+business.phone}>{business.phoneDisplay}</a><span>© {new Date().getFullYear()} ofirma</span></footer></>;
}
