import QuoteForm from '../quote-form';
import type { Metadata } from 'next';
import { ArrowDown, ArrowUpRight, MessageCircle, Ruler, FileText } from 'lucide-react';
import { business, products } from '@/lib/catalog';
export const metadata: Metadata = {title:'Özel Ölçü ve Yedek Konveyör Rulosu | ofirma',description:'Konveyör rulosu için dış çap, gövde boyu, mil ölçüsü ve bağlantı detaylarını paylaşın. Ölçü rehberini inceleyin, WhatsApp üzerinden teklif isteyin.',alternates:{canonical:business.siteUrl+'/konveyor-rulosu'}};
import ProductImage from '@/components/product-image';
import RollerDiagram from '@/components/roller-diagram';
export default function Home(){return (<main id="main"><section className="hero wrap" id="urun"><div className="hero-copy"><p className="eyebrow"><span className="orange-dot"/> KONVEYÖR BİLEŞENLERİ / 01</p><h1>Hattınıza uygun.<br/><span>Ölçünüze özel.</span></h1><p className="lead">{products[0].title} için ihtiyacınızı birlikte netleştirelim. Elinizdeki rulonun ölçülerini veya teknik resmini paylaşarak başlayın.</p><div className="hero-actions"><a className="cta" href="#teklif">Rulonuz için teklif isteyin <ArrowUpRight size={20}/></a><a className="text-link" href="#olcu">Nasıl ölçülür? <ArrowDown size={17}/></a></div><div className="hero-tags"><span>Özel ölçü talebi</span><span>Yedek rulo değerlendirmesi</span></div></div>
<ProductImage id="konveyor-rulosu" title="Konveyör rulosu" priority/></section>
<div className="spec-strip wrap"><div><span>ÜRÜN</span><strong>Konveyör rulosu</strong></div><div><span>İHTİYAÇ</span><strong>Yeni hat veya yedek parça</strong></div><div><span>BAŞLANGIÇ</span><strong>Ölçü, fotoğraf, teknik resim</strong></div><a href="#teklif">İhtiyacınızı paylaşın <ArrowUpRight size={23}/></a></div>
<section className="section wrap" id="olcu"><div className="section-head"><p className="eyebrow">01 — TEKNİK BİLGİLER</p><h2>Doğru teklif,<br/>doğru ölçüyle başlar.</h2><p>Bildiklerinizi paylaşmanız yeterli. Eksik ölçüleri ve bağlantı detaylarını görüşmede netleştirebiliriz.</p></div><div className="roller-guide"><RollerDiagram/></div><div className="measure-grid">{[['D','Dış çap','Rulo gövdesinin dıştan dışa çapı.'],['B','Gövde boyu','Yalnızca dönen gövdenin uçtan uca uzunluğu.'],['d','Mil çapı','Gövde dışına çıkan milin çapı.'],['L','Toplam mil boyu','Milin iki ucu arasındaki toplam uzunluk.']].map(([letter,title,desc])=><article key={letter}><span className="measure-letter">{letter}</span><h3>{title}</h3><p>{desc}</p><span className="unit">Birim: mm</span></article>)}</div><p className="technical-note"><FileText size={18}/> Mil ucu, rulman, malzeme, yük ve çalışma ortamı da seçimde değerlendirilir. Şema bir ölçü rehberidir; üretim teknik resmi değildir.</p></section>
<section className="process-section" id="surec"><div className="wrap"><div className="process-heading"><p className="eyebrow">02 — BİRLİKTE NETLEŞTİRELİM</p><h2>Parçadan başlayın.<br/>Detayları konuşalım.</h2></div><div className="steps">{[['01','İhtiyacınızı paylaşın','Mevcut rulonun ölçülerini, kullanım yerini ve ihtiyacınız olan adedi belirtin.'],['02','Detayları netleştirelim','Malzeme, mil bağlantısı ve çalışma koşullarını teknik resim veya fotoğraf üzerinden görüşelim.'],['03','Teklifi değerlendirin','Üretim uygunluğu, fiyat ve teslim süresi netleştiğinde teklif üzerinden karar verin.']].map(([num,title,desc])=><article key={num}><span>{num}</span><h3>{title}</h3><p>{desc}</p></article>)}</div></div></section>
<section className="quote-section wrap" id="teklif"><div className="quote-intro"><p className="eyebrow">03 — TEKLİF TALEBİ</p><h2>Ölçü sizden.<br/><span>İlk adım birlikte.</span></h2><p>Formu doldurun; bilgileriniz WhatsApp mesajına dönüşsün. Fotoğrafınızı veya teknik resminizi açılan sohbete ekleyebilirsiniz.</p><a className="contact" href={'https://wa.me/'+business.whatsapp} target="_blank" rel="noopener noreferrer"><MessageCircle/><div><small>Doğrudan WhatsApp</small><strong>{business.phoneDisplay}</strong></div><ArrowUpRight/></a><p className="small-note">Fiyat ve üretim uygunluğu teknik değerlendirme sonrasında netleşir.</p></div><QuoteForm/></section>
<section className="faq wrap"><p className="eyebrow">SIK SORULANLAR</p><div>{[['Bütün ölçüleri bilmiyorsam ne yapmalıyım?','Bildiğiniz ölçüleri girin. Rulonun genel görünüşünü ve mil uçlarını gösteren fotoğrafları WhatsApp görüşmesine ekleyebilirsiniz.'],['Fotoğraf veya teknik resmi nasıl paylaşırım?','Formdan WhatsApp’a geçtikten sonra dosyanızı sohbetin ek düğmesiyle gönderin. Bu sayfa dosya yüklemez ve mesajınızı otomatik göndermez.'],['Fiyatı ve teslim süresini ne belirler?','Ölçüler, malzeme, adet, mil ve rulman detayları ile çalışma koşulları birlikte değerlendirilir. Fiyat ve teslim süresi teklif aşamasında netleşir.']].map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></section>
</main>);}

